version: '3.8'

networks:
  fanup:
    driver: bridge

services:
  zookeeper:
    container_name: blockchain-zookeeper
    image: bitnami/zookeeper
    networks:
      - fanup
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: blockchain-kafka
    image: bitnami/kafka
    networks:
      - fanup
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
